# Site settings
title: Meiraki
email: "meiraki-qro@hotmail.com"
description: "Jabones Artesanales y Terapéuticos"
url: "https://meiraki.com.mx"
#baseurl: "/"
facebook_username: "Meiraki-Jabones-Artesanales-y-Terapéuticos-1638400379769477"
twitter_username: false
instagram_username: "meiraki_qro"
github_username:  false
deviantart_username: false
flickr_username: false
discus_shortname: false
share: false

# Owner/author information
owner:
  name:   meiraki
  avatar: avatar.png
  favicon: favicon.ico
  info: photography website template

# Settings for comments helper
# Set 'provider' to the comment provider you want to use. (i.e.  Disqus, Intense Debate, livefyre, or Facebook Comments)
# Set 'provider' to false to turn commenting off globally.
#Set 'provider: false' to disable comments globally.
# Disable comments for individual pages/posts by specifying 'comments: false' in the page/post YAML Front Matter.
#
comments : 
  provider : false
  disqus :
    short_name : ""

# Internal nav
nav:
  - CATÁLOGO: "https://meiraki.github.io/meiraki.github.io/gallery/"  
  - CONTACTO: "https://meiraki.com.mx/about/"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# SiteMap
sitemap:
    file: "/sitemap.xml"
    exclude:
        - "/atom.xml"
        - "/feed.xml"
        - "/feed/index.xml"
    include_posts:
        - "/writing/"
    change_frequency_name: "change_frequency"
    priority_name: "priority"
